const common: Record<string, Record<string, string>> = {
    en: {
        heading: "What should we research?", research: "Research", home: "Home", search: "Search", explore: "Explore", notifications: "Notifications", profile: "Profile",
        comments: "Comments", captured: "✓ Post and comments collected", agent: "Agent", sources: "168 sources · 3 platforms",
        typing: "Composing a research question", opening: "Opening Instagram, X and TikTok", writing: "Comparing evidence across platforms", complete: "Research complete",
        instagramSearch: "Searching Instagram", instagramRead: "Opening a post · reading comments", xSearch: "Searching X", xRead: "Scrolling posts · collecting replies", tiktokSearch: "Searching TikTok", tiktokRead: "Watching videos · checking creator profiles",
        posts: "posts", sourceUnit: "sources", region: "Automated social research examples across Instagram, X and TikTok",
    },
    zh: {
        heading: "想调研什么？", research: "开始调研", home: "首页", search: "搜索", explore: "发现", notifications: "通知", profile: "个人主页",
        comments: "评论", captured: "✓ 已收集帖子和评论", agent: "Agent", sources: "168 个来源 · 3 个平台",
        typing: "正在输入调研问题", opening: "正在打开 Instagram、X 和 TikTok", writing: "正在对比跨平台证据", complete: "调研完成",
        instagramSearch: "正在 Instagram 搜索", instagramRead: "正在打开帖子 · 阅读评论", xSearch: "正在 X 搜索", xRead: "正在滚动帖子 · 收集回复", tiktokSearch: "正在 TikTok 搜索", tiktokRead: "正在查看视频 · 核对达人主页",
        posts: "篇帖子", sourceUnit: "个来源", region: "Instagram、X 和 TikTok 自动调研示意",
    },
};

// Fictional research fixtures for the animated marketing demo, not live results.
const scenarios: Record<string, Record<string, string>>[] = [
    {
        "en": {
            "caseLabel": "01 / BEAUTY TRENDS",
            "question": "Find sunscreen and skincare trends on Instagram, X and TikTok. Which product needs and content angles should a beauty brand prioritize?",
            "queryInstagram": "daily sunscreen texture review",
            "queryX": "\"sunscreen\" \"under makeup\"",
            "queryTiktok": "sunscreen routine review",
            "igName1": "daily.skin.edit",
            "igName2": "beauty.shelf.notes",
            "igName3": "routine.review",
            "igMeta": "Beauty & personal care · Trend research",
            "art1": "THE DAILY TEXTURE",
            "art2": "UNDER MAKEUP",
            "art3": "PACK / REFILL / REPEAT",
            "ig1": "My everyday sunscreen test: how it spreads, how it feels after ten minutes, and whether makeup sits well on top. Texture makes the difference for me.",
            "ig2": "Same foundation, three sunscreens. Showing the layering up close — including the one that pilled. Please show the amount and wait time in reviews.",
            "ig3": "Love the idea of a refill, but can I find it easily? Show me the price per refill and how to swap it without a mess.",
            "xName1": "Leah / Beauty notes",
            "xHandle1": "@leah_beautynotes",
            "xName2": "The routine edit",
            "xHandle2": "@routine_edit",
            "xName3": "Shelf check",
            "xHandle3": "@shelf_check",
            "x1": "I keep coming back to the sunscreen that feels comfortable on a workday. Finish, fragrance and how it layers matter more to me than fancy packaging.",
            "x2": "The most helpful beauty reviews show texture in natural light, makeup on top and how it looks later. A filtered first impression tells me very little.",
            "x3": "Refillable skincare sounds good until the refill is out of stock or almost the same price as a new bottle. Availability and savings need to be obvious.",
            "tkName1": "@skin.in.daylight",
            "tkName2": "@beauty.on.repeat",
            "tkTitle1": "Texture in real daylight",
            "tkTitle2": "Does it layer well?",
            "tkBody1": "Close-up application, finish and a later check-in without a beauty filter.",
            "tkBody2": "A side-by-side makeup layering test, with the amount and wait time shown.",
            "tkMetric1": "184K views · 8.2K saves",
            "tkMetric2": "96K views · 4.1K saves",
            "comment1": "Does this pill when you put foundation on top?",
            "comment2": "I included an unfiltered close-up with the same foundation and wait time.",
            "finding": "Beauty opportunity brief",
            "reportTitle1": "01 / Everyday texture matters",
            "report1": "Finish, fragrance and makeup compatibility recur in posts and replies. Make the daily-use experience a priority for product feedback and messaging. [01][02][03]",
            "reportTitle2": "02 / Show comparable results",
            "report2": "Daylight close-ups and layering tests answer specific purchase questions. Test a short, consistent application-to-check-in format. [04][07][08]",
            "reportTitle3": "03 / Refills need practical value",
            "report3": "Refill discussions focus on price, availability and ease of use. Explain the real savings and replenishment process, rather than packaging alone. [05][06]",
            "reportTitle4": "Recommended next step",
            "report4": "Brief creators on texture and makeup-layering demonstrations. Compare saves, product-page clicks and add-to-cart rates; validate demand with customer interviews and product trials."
        },
        "zh": {
            "caseLabel": "01 / 美妆个护趋势",
            "question": "从 Instagram、X 和 TikTok 调研日常防晒与护肤消费趋势，为美妆品牌找出值得优先验证的产品需求和内容方向。",
            "igMeta": "美妆个护 · 趋势调研",
            "art1": "日常肤感",
            "art2": "妆前叠涂",
            "art3": "包装 / 替换 / 复购",
            "ig1": "我的日常防晒实测：好不好推开、十分钟后的肤感、后续底妆能不能服帖。对我来说，质地真的很影响使用体验。",
            "ig2": "同一款粉底，搭配三款防晒。近距离展示叠涂效果，也保留了搓泥的情况。测评请把用量和等待时间说清楚。",
            "ig3": "喜欢替换装的想法，但补充装好买吗？希望看到单次替换成本，以及怎么换才能不弄得到处都是。",
            "x1": "工作日最常拿起的，还是用着舒服的那款防晒。妆效、香味和叠涂体验，比漂亮包装更影响我会不会复购。",
            "x2": "有用的美妆测评应该展示自然光下的质地、上妆效果和一段时间后的状态。带滤镜的第一印象参考价值不大。",
            "x3": "护肤品替换装如果经常缺货，或者比整瓶便宜不了多少，就很难坚持买。补货便利和节省金额要讲清楚。",
            "tkTitle1": "自然光下看真实质地",
            "tkTitle2": "叠涂底妆会怎样？",
            "tkBody1": "无美颜近拍涂抹、成膜后的妆效，以及一段时间后的状态。",
            "tkBody2": "同款粉底的叠涂对比，明确展示用量和等待时间。",
            "tkMetric1": "18.4 万播放 · 8,200 收藏",
            "tkMetric2": "9.6 万播放 · 4,100 收藏",
            "comment1": "后面叠涂粉底会搓泥吗？",
            "comment2": "视频里有无滤镜近拍，用的是同款粉底和相同等待时间。",
            "finding": "美妆趋势与机会摘要",
            "reportTitle1": "01 / 日常肤感决定偏好",
            "report1": "妆效、香味和底妆兼容性在帖子与评论中反复出现。产品反馈与传播应优先聚焦真实日用体验。[01][02][03]",
            "reportTitle2": "02 / 可对比的实测更有用",
            "report2": "自然光近拍和叠涂测试能回答具体购买问题。可测试「涂抹—上妆—后续状态」的统一短视频形式。[04][07][08]",
            "reportTitle3": "03 / 替换装要有实际价值",
            "report3": "讨论集中在价格、是否好买和替换便利性。应讲清实际节省金额与补货流程，而不只展示包装概念。[05][06]",
            "reportTitle4": "建议下一步",
            "report4": "围绕肤感与妆前叠涂给达人制定实测简报，对比收藏、商品页点击和加购表现；再通过用户访谈与产品试用验证需求。"
        }
    },
    {
        "en": {
            "caseLabel": "02 / SPORTS CREATORS",
            "question": "Find creators for a running-apparel launch across Instagram, X and TikTok. Prioritize runner audiences, useful engagement and real wear tests.",
            "queryInstagram": "running gear review creator",
            "queryX": "\"running shorts\" \"review\"",
            "queryTiktok": "running outfit wear test",
            "igName1": "maya.miles",
            "igName2": "jordan.gearlog",
            "igName3": "sofia.outside",
            "igMeta": "Sports & outdoors · Creator research",
            "art1": "MAYA / EVERYDAY MILES",
            "art2": "JORDAN / GEAR TEST",
            "art3": "SOFIA / OUTSIDE",
            "ig1": "Maya Brooks · 42K followers. Everyday running and run-club content. Comments ask about sizing, phone pockets and how the shorts feel after a long run.",
            "ig2": "Jordan Lee · 28K followers. Detailed running-gear tests, with fit, seams and durability notes carried into follow-up threads on X.",
            "ig3": "Sofia Chen · 86K followers. Running outfits, weekend hikes and outdoor lifestyle. Broad reach; the share of active runners needs checking.",
            "xName1": "Maya Brooks",
            "xHandle1": "@maya_miles",
            "xName2": "Jordan Lee",
            "xHandle2": "@jordan_gearlog",
            "xName3": "Sofia Chen",
            "xHandle3": "@sofia_outside",
            "x1": "The shorts from my long-run video: size worn, pocket fit and what I would change. The phone stayed put, but I would prefer a wider waistband.",
            "x2": "Three runs and five washes later: here are the seams, waistband and fit. A first try-on alone is not enough for a gear recommendation.",
            "x3": "Sharing the kit from our weekend trail walk. Which pieces would you want to see in a longer wear test?",
            "tkName1": "@maya.miles",
            "tkName2": "@sofia.outside",
            "tkTitle1": "10K run. Real wear test.",
            "tkTitle2": "From city to trail",
            "tkBody1": "Maya checks pocket bounce, fit and comfort before and after a run.",
            "tkBody2": "Sofia pairs outdoor outfits with approachable weekend routes.",
            "tkMetric1": "62K views · 3.4K saves",
            "tkMetric2": "210K views · 6.8K saves",
            "comment1": "What size are you wearing, and does a phone bounce in the pocket?",
            "comment2": "Size M — I added a pocket test during the run and a post-run fit check.",
            "finding": "Running creator shortlist",
            "reportTitle1": "01 / Maya Brooks · core audience",
            "report1": "42K Instagram followers; running-led TikToks. Sizing and pocket questions suggest product interest from active runners. Prioritize a real-run wear test. [01][02][07]",
            "reportTitle2": "02 / Jordan Lee · gear credibility",
            "report2": "28K Instagram followers; detailed X reviews. Repeated-use and wash tests suit a brief about fit, construction and durability. [03][04]",
            "reportTitle3": "03 / Sofia Chen · broader reach",
            "report3": "86K Instagram followers; wider outdoor reach on TikTok. Consider for awareness, after checking the running audience share and target-market coverage. [05][06][08]",
            "reportTitle4": "Recommended pilot",
            "report4": "Shortlist Maya and Jordan for run-and-wash tests with tracked product links. Verify audience analytics, past sponsorships and rates; compare qualified visits, add-to-cart and sales, not views alone."
        },
        "zh": {
            "caseLabel": "02 / 运动户外达人",
            "question": "为跑步服饰品牌上新，在 Instagram、X 和 TikTok 筛选合作达人，重点看跑者受众、有效互动和真实穿着测评能力。",
            "igMeta": "运动户外 · 达人筛选",
            "art1": "MAYA / 日常跑步",
            "art2": "JORDAN / 装备实测",
            "art3": "SOFIA / 户外生活",
            "ig1": "Maya Brooks · 4.2 万粉丝。日常跑步与跑团内容，评论常询问尺码、手机口袋和长距离跑后的穿着感受。",
            "ig2": "Jordan Lee · 2.8 万粉丝。细致的跑步装备实测，在 X 补充版型、接缝和多次穿洗后的表现。",
            "ig3": "Sofia Chen · 8.6 万粉丝。跑步穿搭、周末徒步和户外生活方式，触达较广，活跃跑者占比仍需核验。",
            "x1": "长跑视频里的短裤：穿的尺码、口袋大小，以及我想改进的地方。手机固定得住，但腰头如果更宽一点会更好。",
            "x2": "跑了三次、洗了五次，再来看看接缝、腰头和版型。只做一次试穿，不足以判断一件跑步装备。",
            "x3": "分享周末步道散步的整套装备。哪几件是大家想看长期穿着测评的？",
            "tkTitle1": "跑完 10 公里再评价",
            "tkTitle2": "从城市跑向户外",
            "tkBody1": "Maya 对比跑前跑后，检查口袋晃动、版型和舒适度。",
            "tkBody2": "Sofia 将户外穿搭与容易参与的周末路线结合。",
            "tkMetric1": "6.2 万播放 · 3,400 收藏",
            "tkMetric2": "21 万播放 · 6,800 收藏",
            "comment1": "穿的什么尺码？手机放口袋里会晃吗？",
            "comment2": "M 码，视频里补了跑动中的口袋测试和跑后版型对比。",
            "finding": "跑步服饰达人候选",
            "reportTitle1": "01 / Maya Brooks · 核心跑者",
            "report1": "Instagram 4.2 万粉丝，TikTok 以跑步内容为主。尺码和口袋问题体现产品兴趣，优先考虑真实跑步穿测。[01][02][07]",
            "reportTitle2": "02 / Jordan Lee · 装备深度",
            "report2": "Instagram 2.8 万粉丝，在 X 发布细致装备评价。多次穿着与洗涤测试适合解释版型、做工和耐用性。[03][04]",
            "reportTitle3": "03 / Sofia Chen · 广泛触达",
            "report3": "Instagram 8.6 万粉丝，TikTok 覆盖更广的户外人群。适合认知型内容，但应先核验跑者占比及目标市场覆盖。[05][06][08]",
            "reportTitle4": "建议合作路径",
            "report4": "先将 Maya 与 Jordan 列入试投名单，策划带追踪商品链接的跑步与洗涤测试。核验受众数据、历史商单和报价，以有效访问、加购和成交评估。"
        }
    }
];

export const demoScenarioCount = scenarios.length;
export function getDemoCopy(language: string, scenario = 0): Record<string, string> {
    const entry = scenarios[scenario % scenarios.length];
    return { ...common.en, ...common[language], ...entry.en, ...entry[language] };
}
export const demoCopy = { en: getDemoCopy("en"), zh: getDemoCopy("zh") };
